### PR TITLE
[GOVCMSD9-161] Put govcms8_foundations and its sub modules into deprecated folder

### PR DESCRIPTION
**Pull request by pandaskii**

### CODE REVIEW

**Comment by eleonel** [comment]
Hi @pandaskii , thanks for the release.

I tried a fresh migration from GovCMS8 using this release tag and now the process is way easier. The only problem that I had is the one I mentioned to you before: there are some configuration files that can't be install because we already have data in the DB:

```
Unable to install GovCMS Modifiers, core.entity_form_display.paragraph.color_background_modifier.default, core.entity_form_display.paragraph.custom_linear_gradient_modifier.default, core.entity_form_display.paragraph.image_bg_modifier.default, core.entity_form_display.paragraph.padding_modifier.default, core.entity_form_display.paragraph.parallax_bg_modifier.default, core.entity_form_display.paragraph.relative_height_modifier.default, core.entity_view_display.paragraph.color_background_modifier.default, core.entity_view_display.paragraph.color_background_modifier.preview, core.entity_view_display.paragraph.custom_linear_gradient_modifier.default, core.entity_view_display.paragraph.custom_linear_gradient_modifier.preview, core.entity_view_display.paragraph.image_bg_modifier.default, core.entity_view_display.paragraph.image_bg_modifier.preview, core.entity_view_display.paragraph.padding_modifier.default, core.entity_view_display.paragraph.padding_modifier.preview, core.entity_view_display.paragraph.parallax_bg_modifier.default, core.entity_view_display.paragraph.parallax_bg_modifier.preview, core.entity_view_display.paragraph.relative_height_modifier.default, core.entity_view_display.paragraph.relative_height_modifier.preview, field.field.paragraph.color_background_modifier.field_mod_bc_bg_color_val, field.field.paragraph.color_background_modifier.field_mod_bc_bg_h_color_val, field.field.paragraph.color_background_modifier.field_mod_media_query, field.field.paragraph.color_background_modifier.field_mod_transition_duration, field.field.paragraph.custom_linear_gradient_modifier.field_mod_cl_gradient_colors, field.field.paragraph.custom_linear_gradient_modifier.field_mod_cl_gradient_direction, field.field.paragraph.custom_linear_gradient_modifier.field_mod_media_query, field.field.paragraph.image_bg_modifier.field_mod_bgi_color_val, field.field.paragraph.image_bg_modifier.field_mod_image, field.field.paragraph.image_bg_modifier.field_mod_image_position, field.field.paragraph.image_bg_modifier.field_mod_image_style, field.field.paragraph.image_bg_modifier.field_mod_media_query, field.field.paragraph.padding_modifier.field_mod_media_query, field.field.paragraph.padding_modifier.field_mod_padding_b_size, field.field.paragraph.padding_modifier.field_mod_padding_b_units, field.field.paragraph.padding_modifier.field_mod_padding_l_size, field.field.paragraph.padding_modifier.field_mod_padding_l_units, field.field.paragraph.padding_modifier.field_mod_padding_r_size, field.field.paragraph.padding_modifier.field_mod_padding_r_units, field.field.paragraph.padding_modifier.field_mod_padding_t_size, field.field.paragraph.padding_modifier.field_mod_padding_t_units, field.field.paragraph.parallax_bg_modifier.field_mod_bgp_color_val, field.field.paragraph.parallax_bg_modifier.field_mod_media_query, field.field.paragraph.parallax_bg_modifier.field_mod_parallax, field.field.paragraph.parallax_bg_modifier.field_mod_parallax_speed, field.field.paragraph.relative_height_modifier.field_mod_media_query, field.field.paragraph.relative_height_modifier.field_mod_relative_height, field.field.paragraph.relative_height_modifier.field_mod_vertical_align, field.storage.paragraph.field_mod_background_color_val, field.storage.paragraph.field_mod_bc_bg_color_val, field.storage.paragraph.field_mod_bc_bg_h_color_val, field.storage.paragraph.field_mod_bgi_color_val, field.storage.paragraph.field_mod_bgp_color_val, field.storage.paragraph.field_mod_cl_gradient_colors, field.storage.paragraph.field_mod_cl_gradient_direction, field.storage.paragraph.field_mod_h_background_color_val, field.storage.paragraph.field_mod_h_link_color_val, field.storage.paragraph.field_mod_h_text_color_val, field.storage.paragraph.field_mod_image, field.storage.paragraph.field_mod_image_position, field.storage.paragraph.field_mod_image_style, field.storage.paragraph.field_mod_link_color_val, field.storage.paragraph.field_mod_media_query, field.storage.paragraph.field_mod_padding_b_size, field.storage.paragraph.field_mod_padding_b_units, field.storage.paragraph.field_mod_padding_l_size, field.storage.paragraph.field_mod_padding_l_units, field.storage.paragraph.field_mod_padding_r_size, field.storage.paragraph.field_mod_padding_r_units, field.storage.paragraph.field_mod_padding_t_size, field.storage.paragraph.field_mod_padding_t_units, field.storage.paragraph.field_mod_parallax, field.storage.paragraph.field_mod_parallax_speed, field.storage.paragraph.field_mod_relative_height, field.storage.paragraph.field_mod_text_color_val, field.storage.paragraph.field_mod_transition_duration, field.storage.paragraph.field_mod_vertical_align, field.storage.paragraph.field_modifiers, paragraphs.paragraphs_type.color_background_modifier, paragraphs.paragraphs_type.custom_linear_gradient_modifier, paragraphs.paragraphs_type.image_bg_modifier, paragraphs.paragraphs_type.padding_modifier, paragraphs.paragraphs_type.parallax_bg_modifier, paragraphs.paragraphs_type.relative_height_modifier already exist in active configuration.
```

So I did this trick to install the module:

```
mv profiles/govcms/modules/custom/core/govcms_foundations/modules/govcms_modifiers/config profiles/govcms/modules/custom/core/govcms_foundations/modules/govcms_modifiers/_config
```

Install the module drush en -y govcms_modifiers

And then rename the folder back:

```
mv profiles/govcms/modules/custom/core/govcms_foundations/modules/govcms_modifiers/_config profiles/govcms/modules/custom/core/govcms_foundations/modules/govcms_modifiers/config
```

After doing that the website looks identical to the original govcms8 site.

**Comment by pandaskii** [comment]
@eleonel thanks for the feedbacks 

Had thought this PR would be helpful :)

**Comment by eleonel** [comment]
> @eleonel thanks for the feedbacks
> 
> Had thought this PR would be helpful :)

looking good @pandaskii

**Comment by Gumnutt** [comment]
Changing the name of the module seems fine, people aren't encouraged to use it as it's depreciated.

**Pull request merged**
